name: brightonmapbot

on:
  schedule:
    - cron: '19 * * * *'  # run once every hour at 19 minutes past the hour

jobs:
  brighton-mapbot-post:
    runs-on: macOS-latest
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      TWITTER_MAPBOT_ACCESS_TOKEN: ${{ secrets.TWITTER_MAPBOT_ACCESS_TOKEN }}
      TWITTER_MAPBOT_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_MAPBOT_ACCESS_TOKEN_SECRET }}
      MAPBOX_PUBLIC_ACCESS_TOKEN: ${{ secrets.MAPBOX_PUBLIC_ACCESS_TOKEN  }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: install package rtweet + dependencies
        run: echo "about to install rtweet..."
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE, repos = "http://cran.us.r-project.org")'
        run: echo "...done installing rtweet"
      - name: grab frame, compose tweet, and post to twitter tweet
        run: Rscript bot.R
        run: echo "all done"
