name: brighton_mapbot

on:
  schedule:
    - cron '0 */6 * * *'

jobs:
  brighton-mapbot-post:
    runs-on: macOS-latest
    env:
      TWITTER_API_KEY = {{ secrets.TWITTER_API_KEY }}
      TWITTER_API_KEY_SECRET = {{ secrets.TWITTER_API_KEY_SECRET }}
      TWITTER_BEARER_TOKEN = {{ secrets.TWITTER_BEARER_TOKEN }}
      TWITTER_MAPBOT_ACCESS_TOKEN = {{ secrets.TWITTER_MAPBOT_ACCESS_TOKEN }}
      TWITTER_MAPBOT_ACCESS_TOKEN_SECRET = {{ secrets.TWITTER_MAPBOT_ACCESS_TOKEN_SECRET }}
      MAPBOX_PUBLIC_ACCESS_TOKEN = {{ secrets.MAPBOX_PUBLIC_ACCESS_TOKEN  }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rtweet
          needs: check
      - name: install package rtweet + dependencies
        run: Rscript -e "install.packages('rtweet', dependencies = TRUE)"
      - name: Create and post tweet
        run: Rscript bot.R
